Remove rebar and use a Makefile instead of bash

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,67 +1,16 @@
 #!/bin/bash
 
-##
-# usage: bin/compile <build-dir> <cache-dir>
+# usage: bin/compile <build-dir> <cache-dir> <env-dir>
 
-set -e
-bpdir=$(cd $(dirname $(dirname $0)); pwd)
-mkdir -p "$1" "$2"
-build=$(cd "$1/" && pwd)
-test -z ${build} && exit
-cache=$(cd "$2/" && pwd)
-test -z ${cache} && exit
-DEFAULT_OTP_VERSION="master"
-if [ -f ${build}/.preferred_otp_version ]; then
-    OTP_VERSION=$(cat ${build}/.preferred_otp_version)
-fi
-ver=${OTP_VERSION:=${DEFAULT_OTP_VERSION}}
-tarball=${ver}.tgz
-OTP_TARBALL_URL="https://s3.amazonaws.com/heroku-buildpack-erlang/${tarball}"
-ERLROOT=${build}/otp
-PROFILE=${HOME}/.profile.d
+set -x
 
-echo "-----> Using Erlang/OTP $ver"
+set -eo pipefail
 
-(
-    set -e
+SCRIPT_DIR=$(dirname $0)
+test -n "$1" -a -n "$2" -a -n "$3" || (echo "Missing arguments!" && exit 1)
 
-    # Already cached?
-    test -f ${cache}/${tarball} && exit
+export BUILD_DIR=$1
+export CACHE_DIR=$2
+export ENV_DIR=$3
 
-    rm -rf ${cache}/* # be sure not to build up cruft
-    cd ${cache}
-    echo "-------> Fetching Erlang/OTP $ver"
-    curl -sO ${OTP_TARBALL_URL} || exit 1
-)
-
-echo "-------> Unpacking Erlang/OTP $ver"
-mkdir -p ${ERLROOT}
-tar zxf ${cache}/${tarball} -C ${ERLROOT} --strip-components=2
-echo "-------> Installing Erlang/OTP $ver"
-ln -s ${ERLROOT} /app/otp
-${ERLROOT}/Install -minimal /app/otp
-
-PATH=/app/otp/bin:$PATH
-export PATH
-
-cd $build
-
-if [ ! -e "rebar" ]; then
-  echo "-----> Installing Rebar from buildpack"
-  cp ${bpdir}/opt/rebar ./
-fi
-
-echo "-----> Building with Rebar"
-unset GIT_DIR
-./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-  echo "-----> Build failed"
-  exit 1
-fi
-
-if [ -f ${bpdir}/opt/otp.sh ]; then
-  mkdir -p ${PROFILE}
-  cp ${bpdir}/opt/otp.sh ${PROFILE}
-fi
-
-echo "-----> Build succeeded"
+make --debug -f ${SCRIPT_DIR}/$(basename $0).mk
